spring.application.name=backend-sgo
spring.datasource.url=jdbc:postgresql://localhost/sgo-db
spring.datasource.username=postgres
spring.datasource.password=postgres123
jwt.secret=A7x29KsPasteristico91LmQLAFippSistemaJWT2026UltraSecretSGO